#
# This is a flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1) for more information
#

# List packages you wish to install in your environment inside
# the 'install' section

[install]
chezmoi.pkg-path = "chezmoi"
neovim.pkg-path = "neovim"
zsh.pkg-path = "zsh"
git.pkg-path = "git"
gh.pkg-path = "gh"
eza.pkg-path = "eza"
tmux.pkg-path = "tmux"
delta.pkg-path = "delta"
ripgrep.pkg-path = "ripgrep"
nodejs_21.pkg-path = "nodejs_21"
fzf.pkg-path = "fzf"
cmake.pkg-path = "cmake"
gnumake.pkg-path = "gnumake"
unzip.pkg-path = "unzip"
lua-language-server.pkg-path = "lua-language-server"
libcxx.pkg-path = "llvmPackages_17.libcxx"
lldb.pkg-path = "llvmPackages_17.lldb"
libcxxabi.pkg-path = "llvmPackages_17.libcxxabi"
libcxxClang.pkg-path = "llvmPackages_17.libcxxClang"
clang-tools_17.pkg-path = "clang-tools_17"
gopls.pkg-path = "gopls"
go.pkg-path = "go"
cargo.pkg-path = "cargo"
starship.pkg-path = "starship"
go-task.pkg-path = "go-task"

# Set an environment variable.
# These variables may not reference once another
# and are added to the environment without expansion.
[vars]
EDITOR = "nvim"
GH_EDITOR = "nvim"
VISUAL = "nvim"

# An environment that works on one system is guaranteed to work on the
# same type of system,
# but other systems may not have the same packages available, etc.
# In order to use the environment on a system you must explicitly
# add it to this list.
[options]
systems = ["x86_64-linux"]
