#!/usr/bin/env python3
import signal
import sys
import subprocess

proc = None

def signal_handler(sig, frame):
    if proc:
        print('Terminating process')
        proc.terminate()
        try:
            proc.wait(1)
        except:
            print('Killing process')
            proc.kill()
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

while True:
    proc = subprocess.Popen(sys.argv[1:])
    retcode = proc.wait()
    if retcode == 0:
        break
