# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [ -d $HOME/.zshrc.d ]; then
  for i in $HOME/.zshrc.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

# bun completions
[ -s "/home/rockwood/.bun/_bun" ] && source "/home/rockwood/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
